language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - ./ci/start-ci.sh $ORIENTDB_VERSION
  - composer install --prefer-source

script: ./vendor/bin/phpunit

env:
  - ORIENTDB_VERSION=2.0-M3
  - ORIENTDB_VERSION=2.0-M2
#  - ORIENTDB_VERSION=1.7.10
  - ORIENTDB_VERSION=1.7.8
  - ORIENTDB_VERSION=1.7.7
  - ORIENTDB_VERSION=1.7.4

matrix:
  allow_failures:
    - env: ORIENTDB_VERSION=1.7.4
